    var Theme = [
    {
        startlayer_bg: s_background1,
        gamelayer_bg: s_background3,
        storelayer_bg: s_background,
        info_bg: s_background2,
        menu: s_start_menu,
        hook: s_hook,
        big_rock: s_big_rock,
        small_rock: s_small_rock,
        big_gold: s_big_gold,
        middle_gold: s_middle_gold,
        small_gold: s_small_gold,
        pig: s_pig,
        big_diamond: s_big_diamond,
        small_diamond: s_small_diamond,
        bomb: s_bomb,
        bone: s_bone,
        milk: s_milk,
        clock: s_clock,
        money_tree: s_money_tree,
        rich: s_rich,
        accept: s_accept,
        bat: s_bat
    },
    {
        startlayer_bg: s_background1,
        gamelayer_bg: s_background3,
        storelayer_bg: s_background,
        info_bg: s_background2,
        menu: s_start_menu,
        hook: s_hook,
        big_rock: s_big_rock,
        small_rock: s_small_rock,
        big_gold: s_big_gold,
        small_gold: s_small_gold,
        pig: s_pig,
        big_diamond: s_big_diamond,
        small_diamond: s_small_diamond,
        bomb: s_bomb,
        bone: s_bone,
        milk: s_milk,
        clock: s_clock,
        money_tree: s_money_tree,
        rich: s_rich,
        accept: s_accept
    }
];